{
 "title": "Hazelcast",
 "description": "Shows Hazelcast, JVM and usage metrics",
 "tags": [
  "JVM",
  "hazelcast"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(com_hazelcast_Metrics_uptime, instance)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(com_hazelcast_Metrics_uptime, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Hazelcast", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "JVM Threads State",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (state) (jvm_threads_state{job=\"$job\",instance=\"$instance\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (com_hazelcast_Metrics_uptime)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hazelcast Active Count",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (com_hazelcast_Metrics_activeCount{job=\"$job\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Map Statistics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_getCount{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "get-{{tag0}}"
    },
    {
     "expr": "com_hazelcast_Metrics_putCount{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "put-{{tag0}}"
    },
    {
     "expr": "com_hazelcast_Metrics_removeCount{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "remove-{{tag0}}"
    }
   ]
  },
  {
   "title": "Maps latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalGetLatency{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "get-{{tag0}}"
    },
    {
     "expr": "com_hazelcast_Metrics_totalPutLatency{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "put-{{tag0}}"
    },
    {
     "expr": "com_hazelcast_Metrics_totalRemoveLatency{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "remove-{{tag0}}"
    }
   ]
  },
  {
   "title": "Entry Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_backupEntryCount{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "backupentry-{{tag0}}"
    },
    {
     "expr": "com_hazelcast_Metrics_dirtyEntryCount{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "dirty-{{tag0}}"
    },
    {
     "expr": "com_hazelcast_Metrics_lockedEntryCount{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "locked-{{tag0}}"
    }
   ]
  },
  {
   "title": "Hazelcast Partition Thread Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (com_hazelcast_Metrics_partitionThreadCount)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hazelcast Hits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_hits{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{tag0}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{area}} memory"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "current"
    },
    {
     "expr": "jvm_threads_daemon{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "daemon"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=\"$job\",instance=\"$instance\"}[1m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  { "title": "JVM memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{area}} memory"
    }
   ]
  },
  {
   "title": "Memory comitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_committed{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{area}} memory"
    }
   ]
  },
  {
   "title": "Memory pool used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pool) (jvm_memory_pool_bytes_used{job=\"$job\",instance=\"$instance\"})",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Memory pool committed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pool) (jvm_memory_pool_bytes_committed{job=\"$job\",instance=\"$instance\"})",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Memory pool collection used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pool) (jvm_memory_pool_collection_used_bytes{job=\"$job\",instance=\"$instance\"})",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Memory pool collection used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pool) (jvm_memory_pool_collection_committed_bytes{job=\"$job\",instance=\"$instance\"})",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Memory pool allocated total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pool) (jvm_memory_pool_allocated_bytes_total{job=\"$job\",instance=\"$instance\"})",
     "legendFormat": "{{pool}}"
    }
   ]
  }
 ]
}